version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9.3

    working_directory: /go/src/github.com/alpacahq/marketstore
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/...
      - run: make configure all plugins

  test:
    docker:
      - image: circleci/golang:1.9.3

    working_directory: /go/src/github.com/alpacahq/marketstore
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/...
      - run: make configure unittest
  
  deploy:
    docker:
      - image: circleci/golang:1.9.3

    working_directory: /go/src/github.com/alpacahq/marketstore
    steps:
      - checkout
      - setup_remote_docker
      - run: go get -u github.com/golang/dep/...
      - run: DOCKER_TAG=$CIRCLE_TAG make configure push

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
