version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9.3

    working_directory: /go/src/github.com/alpacahq/marketstore
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/...
      - run: make configure all plugins

  test:
    docker:
      - image: circleci/golang:1.9.3

    working_directory: /go/src/github.com/alpacahq/marketstore
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/...
      - run: make configure unittest

  deploy:
    docker:
      - image: circleci/golang:1.9.3

    working_directory: /go/src/github.com/alpacahq/marketstore
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/...
      - run: BUILD_TAG=$(CIRCLE_TAG) DOCKER_TAG=$(CIRCLE_BRANCH) make configure push

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
